#!/bin/bash

echo "🚀 GitHub Pages Deployment Setup"
echo ""
echo "This script will help you set up automatic deployment to GitHub Pages."
echo ""
echo "You have two options:"
echo ""
echo "Option 1: Manual Setup (Recommended - 2 minutes)"
echo "==========================================="
echo "1. Go to: https://github.com/arikagan/cosmic-todo/new/main"
echo "2. Create file: .github/workflows/deploy.yml"
echo "3. Copy the workflow content from the file: .github/workflows/deploy.yml"
echo "4. Commit the file"
echo ""
echo "Then add GitHub Secrets:"
echo "5. Go to: https://github.com/arikagan/cosmic-todo/settings/secrets/actions"
echo "6. Add these secrets (click 'New repository secret' for each):"
echo ""
cat .env | grep VITE_ | while read line; do
    name=$(echo $line | cut -d= -f1)
    value=$(echo $line | cut -d= -f2-)
    echo "   Name: $name"
    echo "   Value: $value"
    echo ""
done
echo ""
echo "7. Enable GitHub Pages:"
echo "   Go to: https://github.com/arikagan/cosmic-todo/settings/pages"
echo "   Source: GitHub Actions"
echo ""
echo "8. Add your GitHub Pages URL to Firebase:"
echo "   Go to: https://console.firebase.google.com/"
echo "   Authentication → Settings → Authorized domains"
echo "   Add: arikagan.github.io"
echo ""
echo "=========================================="
echo ""
echo "Option 2: Quick copy-paste guide"
echo "==========================================="
echo "Run this to see the workflow file content:"
echo "  cat .github/workflows/deploy.yml"
echo ""
